[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "value_iteration"
version = "0.0.0"
maintainers = [
  { name="Tina Sardashti", email="t.sardashti@lancaster.ac.uk" },
]

authors = [
  { name="Tina Sardashti", email="t.sardashti@lancaster.ac.uk" },
]

description = "A Python package implementing the value iteration algorithm for solving Markov Decision Processes"

requires-python = ">=3.13.10"

classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent",
]

dependencies = ["pytest"]

[project.urls]
homepage = "https://github.com/tinasardashti/value_iteration_project"
